name: Check Pizza 4P's Slots

on:
  schedule:
    - cron: '*/30 * * * *'  # Run every 30 minutes
  workflow_dispatch:  # Allow manual trigger

jobs:
  check-slots:
    runs-on: ubuntu-latest
    steps:
      - name: Debug before checkout
        run: |
          echo "Current directory before checkout:"
          pwd
          ls -la

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Debug after checkout
        run: |
          echo "Current directory after checkout:"
          pwd
          ls -la
          echo "\nRepository contents:"
          find . -type f
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          
      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser chromium-chromedriver
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium webdriver-manager requests schedule beautifulsoup4
          
      - name: Run slot checker
        env:
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        run: python ./slot_checker.py
